import type { BusHotspot } from "./types";

/**
 * Details pinned to the 3D bus in the garage. `x` and `y` are percentages
 * across and down a face: the front and back cutouts, or the side panel
 * measured from the front bumper.
 */
export const busHotspots: readonly BusHotspot[] = [
  {
    face: "front",
    x: 50.8,
    y: 1.7,
    title: "Light bar",
    text: "Sixteen square lamps glowing red across the very top.",
  },
  {
    face: "front",
    x: 34.2,
    y: 7.9,
    title: "Beacon tiers",
    text: "Rows of beacon domes stacked under the light bar, alternating purple and red.",
  },
  {
    face: "front",
    x: 45.6,
    y: 20.2,
    title: "The MOOD banner",
    text: "MOOD in white graffiti letters with two faces set into the O's, on a lilac wash full of melting smileys.",
  },
  {
    face: "front",
    x: 51.8,
    y: 30.1,
    title: "No risk, no story",
    text: "The motto across the bottom of the banner, and the first line of the Instagram bio.",
  },
  {
    face: "front",
    x: 78.8,
    y: 26.4,
    title: "School kills Artists",
    text: "Signed off in red hand lettering on the passenger side.",
  },
  {
    face: "front",
    x: 72.5,
    y: 38.7,
    title: "Sun-strip & credits",
    text: "The blue sun-strip carries shout-outs to Sticker Hub and POOLMAN.",
  },
  {
    face: "front",
    x: 44.6,
    y: 42.4,
    title: "Thou Shall Not TRY ME",
    text: "Gold and purple with a white die-cut edge: a key on the left, flowers on the right, and the script that turns TRY ME into a commandment.",
  },
  {
    face: "front",
    x: 2.1,
    y: 37.5,
    title: "Smiley mirrors",
    text: "Both mirror housings are wrapped in purple with dead-eyed drippy smileys and little MOOD tags.",
  },
  {
    face: "front",
    x: 48.7,
    y: 53.5,
    title: "LED pods",
    text: "Six LED pods in a bar under the windscreen.",
  },
  {
    face: "front",
    x: 49.7,
    y: 63.3,
    title: "Custom grille",
    text: "Purple slats with small red accent lights.",
  },
  {
    face: "front",
    x: 23.8,
    y: 74.4,
    title: "Headlights",
    text: "Angular LED headlights with ice-blue accent strips.",
  },
  {
    face: "front",
    x: 16.6,
    y: 86.7,
    title: "Bumper pods",
    text: "Clusters of small round lamps set into the sculpted bumper.",
  },
  { face: "front", x: 48.7, y: 85.5, title: "The plate", text: "The white MOOD plate." },
  {
    face: "front",
    x: 48.7,
    y: 94.1,
    title: "Fog lights",
    text: "Four square lamps with red cores along the bottom of the bumper.",
  },
  {
    face: "back",
    x: 33.9,
    y: 7.6,
    title: "Roof rack",
    text: "A purple roof rack lined with beacon lights, crowning the tailgate.",
  },
  {
    face: "back",
    x: 27.1,
    y: 32.4,
    title: "The faces",
    text: "Airbrushed, wide-eyed portraits in warm gold tones. Impossible to ignore at a traffic light.",
  },
  {
    face: "back",
    x: 77.1,
    y: 34.6,
    title: "The attitude",
    text: "Tongue out, eyebrow up. Mood's art talks back.",
  },
  {
    face: "back",
    x: 61.2,
    y: 50.8,
    title: "Hazard zone",
    text: "A yellow hazard sign, a red warning triangle, chain-link fence and a smiley hidden in the mix.",
  },
  {
    face: "back",
    x: 32.8,
    y: 58.3,
    title: "Tail lights",
    text: "Sculpted red LED tail lights wrap around the art like a frame.",
  },
  {
    face: "back",
    x: 16.9,
    y: 75.6,
    title: "ATMOSPHERE",
    text: "White cracked lettering across the tailgate. One word for what Mood brings.",
  },
  { face: "back", x: 51.0, y: 75.6, title: "The plate", text: "The yellow rear MOOD plate." },
  {
    face: "back",
    x: 48.7,
    y: 92.9,
    title: "Rear diffuser",
    text: "A race-style purple diffuser. Pure nganya engineering.",
  },
  {
    face: "side",
    x: 50,
    y: 3,
    title: "The crown",
    text: "From the side, the roof is lined end to end with beacon lamps.",
  },
  {
    face: "side",
    x: 22,
    y: 86,
    title: "The rims",
    text: "Black multi-spoke alloys to finish the look.",
  },
];
